spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 10000MB
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    block-when-exhausted: true
    # password: Pass*4
    jedis:
      pool:
        max-idle: 50
        max-wait: 5000