server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 10000MB
  datasource:
    username: root
    password: pass&&1024
    url: jdbc:mysql://101.37.89.200:3306/webmaple?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    block-when-exhausted: true
    # password: Pass*4
    jedis:
      pool:
        max-idle: 50
        max-wait: 5000
mybatis:
  type-aliases-package: com.webmaple.admin.model
  map-underscore-to-camel-case: true